### ISSUE TITLE
pip install -r  requirements.txt  -- ERROR: Invalid requirement: 'torch~=2.1.0+cu121

### ISSUE THREAD

**Issue by chervov** [Eliorkalfon/single_cell_pb#5]
May be I am doing something wrong, but it does not work for me on Kaggle:

!pip install -r  ./single_cell_pb/requirements.txt
ERROR: Invalid requirement: 'torch~=2.1.0+cu121' (from line 3 of ./single_cell_pb/requirements.txt)

Example: 
https://www.kaggle.com/code/alexandervc/scp-top2-eliorkalfon-draft?scriptVersionId=163725742&cellId=4

**Comment by Eliorkalfon** [comment]
Yeah, I suggest commenting this line and install directly from pytorch using : 
pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu121
(It was the latest pytorch version back then)
