### ISSUE TITLE
After training in torch.save(transformer_model.state_dict(), "AttributeError: 'tuple' object has no attribute 'state_dict'"

### ISSUE THREAD

**Issue by chervov** [Eliorkalfon/single_cell_pb#6]
Tried 5 epochs - training seems passed Okay,

But probably during saving 
torch.save(transformer_model.state_dict(),
 got error:
AttributeError: 'tuple' object has no attribute 'state_dict'

https://www.kaggle.com/code/alexandervc/scp-top2-eliorkalfon-draft?scriptVersionId=163742394&cellId=8

torch.__version__
'2.1.2'

**Comment by Eliorkalfon** [comment]
can you try to run with torch version 2.1.0?

**Comment by HelloWorldLTY** [comment]
Hi, I am using torch 2.1.0 and received the same error.

pytorch                   2.1.0           py3.8_cuda12.1_cudnn8.9.2_0    pytorch

**Comment by HelloWorldLTY** [comment]
I replaced the line 199 with the following code after reviewing the content in transformer_model:

```
torch.save(transformer_model[2].state_dict(),
                       f'trained_models_random/transformer_model_{n_components}_{d_model}.pt')
```
