### ISSUE TITLE
predict -  [Errno 2] No such file or directory: 'trained_models/transformer_model_18211_128.p

### ISSUE THREAD

**Issue by chervov** [Eliorkalfon/single_cell_pb#7]
[Errno 2] No such file or directory: 'trained_models/transformer_model_18211_128.p
https://www.kaggle.com/code/alexandervc/scp-top2-eliorkalfon-draft?scriptVersionId=163743907&cellId=11

May it is caused by the previous error
or may be the directory naming do not correspond to config_test / naming  created in predict

**Comment by Eliorkalfon** [comment]
You did not save the models because of the previous error.
Try to download one of my trained models and check if it works.
