### ISSUE TITLE
Question about training data

### ISSUE THREAD

**Issue by HelloWorldLTY** [Eliorkalfon/single_cell_pb#8]
Hi, thanks for your great work and big congs for your award! I am curious about the dataset you used to input as the training dataset. I try to reproduce this work but I found that an error which hints me that training data do not contains observation names. It will be great if you can let me know the details of the pre-processing step.

The file I used to input as adata_train.parquet. Thanks a lot.

**Comment by HelloWorldLTY** [comment]
I think I got the file. Is it de_train.parquet? Thanks.

**Comment by Eliorkalfon** [comment]
Yes, I trained my models on the parsed parquet file which is de_train.parquet.
